services:
  - type: worker                  # фоновый сервис (а не web)
    name: kufar-watcher-bot
    env: python                   # Python-окружение
    pythonVersion: 3.11.9         # ЖЁСТКО: ставим Python 3.11
    buildCommand: |
      python -V                   # покажет версию в логах
      pip install -r requirements.txt
    startCommand: python kufar_bot.py
